[package]
name = "thesis_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickcheck = "1"
quickcheck_macros = "1"
is-root = "0.1.2"
nix = {version = "0.28", features = ["user"]}
